import { createContext, useContext, useState, useEffect } from 'react'

// Traducciones completas para 3 idiomas
const translations = {
  es: {
    // General
    app_name: 'Alqvimia',
    version: 'v2.0',
    connected: 'Conectado',
    disconnected: 'Desconectado',
    server_active: 'Servidor activo',
    click_to_connect: 'Haz clic para conectar',
    expand_menu: 'Expandir menú',
    collapse_menu: 'Contraer menú',

    // Navegación
    nav_spy: 'Element Spy',
    nav_recorder: 'Grabador',
    nav_workflows: 'Workflows',
    nav_executor: 'Ejecutor',
    nav_code_editor: 'Editor de Código',
    nav_agents: 'Agentes',
    nav_mcp: 'MCP Conectores',
    nav_marketplace: 'Marketplace',
    nav_library: 'Biblioteca',
    nav_ai_dashboard: 'IA Dashboard',
    nav_omnichannel: 'Omnicanalidad',
    nav_videoconference: 'Videoconferencia',
    nav_settings: 'Configuraciones',
    nav_scheduler: 'Programador',
    nav_onboarding: 'Asistente',
    nav_admin: 'Administración',

    // Scheduler
    scheduler_subtitle: 'Programa ejecuciones automaticas de tus workflows',
    scheduler_new: 'Nueva Programacion',
    scheduler_active: 'Activas',
    scheduler_paused: 'Pausadas',

    // Botones comunes
    btn_save: 'Guardar',
    btn_cancel: 'Cancelar',
    btn_delete: 'Eliminar',
    btn_edit: 'Editar',
    btn_new: 'Nuevo',
    btn_import: 'Importar',
    btn_export: 'Exportar',
    btn_close: 'Cerrar',
    btn_confirm: 'Confirmar',
    btn_search: 'Buscar',
    btn_filter: 'Filtrar',
    btn_refresh: 'Actualizar',
    btn_run: 'Ejecutar',
    btn_stop: 'Detener',
    btn_pause: 'Pausar',
    btn_continue: 'Continuar',
    btn_copy: 'Copiar',
    btn_paste: 'Pegar',
    btn_duplicate: 'Duplicar',
    btn_download: 'Descargar',
    btn_upload: 'Subir',
    btn_help: 'Ayuda',
    btn_settings: 'Configuración',
    btn_back: 'Volver',
    btn_next: 'Siguiente',
    btn_previous: 'Anterior',
    btn_apply: 'Aplicar',
    btn_reset: 'Restablecer',
    btn_test: 'Probar',
    btn_add: 'Agregar',
    btn_remove: 'Remover',
    btn_select: 'Seleccionar',
    btn_select_all: 'Seleccionar todo',
    btn_clear: 'Limpiar',
    btn_view: 'Ver',
    btn_preview: 'Vista previa',

    // Element Spy
    spy_title: 'Element Spy',
    spy_subtitle: 'Inspecciona y captura selectores de elementos web',
    spy_help_title: '¿Cómo funciona Element Spy?',
    spy_help_intro: 'Element Spy te permite inspeccionar páginas web y capturar selectores de elementos para usar en tus automatizaciones.',
    spy_how_to_use: '¿Cómo usar?',
    spy_step_1: 'Ingresa la URL de la página que deseas inspeccionar',
    spy_step_2: 'Selecciona el modo de operación',
    spy_step_3: 'Haz clic en los elementos para capturar sus selectores',
    spy_step_4: 'Copia el selector que prefieras para usar en tus workflows',
    spy_modes: 'Modos de Operación',
    spy_mode_iframe: 'Modo Iframe',
    spy_mode_iframe_desc: 'Carga la página dentro de Alqvimia. Funciona sin plugins.',
    spy_mode_iframe_features: 'Sin instalación|Rápido|Limitado por CORS',
    spy_mode_bookmarklet: 'Bookmarklet',
    spy_mode_bookmarklet_desc: 'Arrastra el botón a tus marcadores y úsalo en cualquier sitio.',
    spy_mode_bookmarklet_features: 'Funciona en cualquier sitio|Sin límites de CORS|Requiere arrastrar',
    spy_mode_extension: 'Extensión',
    spy_mode_extension_desc: 'Instala la extensión para funcionalidad completa.',
    spy_mode_extension_features: 'Funcionalidad completa|Grabación avanzada|Requiere instalación',
    spy_url_label: 'URL a inspeccionar',
    spy_url_placeholder: 'https://ejemplo.com',
    spy_load_page: 'Cargar Página',
    spy_highlight_color: 'Color de resaltado',
    spy_inspector_title: 'Inspector de Elementos',
    spy_no_element: 'Haz clic en un elemento de la página para inspeccionarlo',
    spy_element_tag: 'Etiqueta',
    spy_element_id: 'ID',
    spy_element_class: 'Clase',
    spy_element_name: 'Name',
    spy_element_text: 'Texto',
    spy_element_xpath: 'XPath',
    spy_selector_options: 'Opciones de Selector',
    spy_copy_selector: 'Copiar',
    spy_add_to_workflow: 'Agregar a Workflow',
    spy_recent_elements: 'Elementos Recientes',
    spy_drag_bookmarklet: 'Arrastra este botón a tu barra de marcadores',

    // Workflows
    wf_title: 'Workflow Studio',
    wf_new: 'Nuevo',
    wf_save: 'Guardar',
    wf_import: 'Importar',
    wf_export: 'Exportar',
    wf_migrate: 'Migrar',
    wf_ai_generate: 'IA',
    wf_code_editor: 'Editor',
    wf_debug: 'Debug',
    wf_actions: 'Acciones',
    wf_properties: 'Propiedades',
    wf_variables: 'Variables',
    wf_search_actions: 'Buscar acciones...',
    wf_drag_here: 'Arrastra acciones aquí para construir tu workflow',
    wf_use_ai: 'O usa el generador con IA para crear workflows automáticamente',
    wf_start: 'Iniciar',
    wf_end: 'Fin',
    wf_steps: 'pasos',
    wf_breakpoints: 'breakpoints',
    wf_clipboard: 'Portapapeles',
    wf_debugging: 'Depurando...',
    wf_list_view: 'Vista de lista',
    wf_flow_view: 'Vista de flujo',
    wf_voice_commands: 'Comandos de voz',
    wf_stop_voice: 'Detener',
    wf_load_more_actions: 'Cargar más acciones',

    // Guardar Workflow
    wf_save_title: 'Guardar Workflow',
    wf_save_name: 'Nombre del Workflow',
    wf_save_location: 'Ubicación de Guardado',
    wf_save_local: 'Almacenamiento Local',
    wf_save_local_desc: 'Guardado en el navegador',
    wf_save_file: 'Descargar Archivo',
    wf_save_file_desc: 'Archivo .alq en tu PC',
    wf_save_folder: 'Carpeta de Destino',
    wf_save_new_folder: 'Nueva Carpeta',
    wf_save_folder_name: 'Nombre de la nueva carpeta...',
    wf_save_summary: 'Resumen',
    wf_save_will_save: 'Se guardará en:',
    wf_folder_my_workflows: 'Mis Workflows',
    wf_folder_production: 'Producción',
    wf_folder_development: 'Desarrollo',
    wf_folder_testing: 'Pruebas',
    wf_folder_templates: 'Plantillas',
    wf_folder_archived: 'Archivados',

    // Categorías de acciones
    cat_control_flow: 'Control de Flujo',
    cat_dialogs: 'Diálogos y Mensajes',
    cat_variables: 'Variables y Datos',
    cat_text: 'Texto y Strings',
    cat_collections: 'Colecciones',
    cat_web_browser: 'Navegador Web',
    cat_active_directory: 'Active Directory',
    cat_ai: 'Inteligencia Artificial',
    cat_database: 'Base de Datos',
    cat_files: 'Archivos y Carpetas',
    cat_email: 'Correo Electrónico',
    cat_excel: 'Excel',
    cat_pdf: 'PDF',
    cat_rest: 'REST / API',
    cat_sap: 'SAP',
    cat_microsoft365: 'Microsoft 365',
    cat_mouse_keyboard: 'Mouse & Keyboard',
    cat_windows: 'Windows / Sistema',
    cat_ocr_image: 'OCR e Imágenes',
    cat_credentials: 'Credenciales',

    // OCR Settings
    ocr_title: 'Configuración de OCR',
    ocr_subtitle: 'Configura proveedores de reconocimiento óptico de caracteres. Selecciona un motor y configura sus credenciales.',
    ocr_tesseract: 'Tesseract OCR',
    ocr_tesseract_desc: 'Motor OCR de código abierto. Funciona sin conexión a internet.',
    ocr_free: 'GRATUITO',
    ocr_cloud: 'CLOUD',
    ocr_offline: 'Offline',
    ocr_languages: 'idiomas',
    ocr_open_source: 'Open Source',
    ocr_azure: 'Azure Computer Vision',
    ocr_azure_desc: 'OCR empresarial de Microsoft con IA avanzada y alta precisión.',
    ocr_advanced_ai: 'IA Avanzada',
    ocr_tables_forms: 'Tablas/Forms',
    ocr_handwriting: 'Escritura a mano',
    ocr_google: 'Google Cloud Vision',
    ocr_google_desc: 'OCR potente de Google con detección de objetos y etiquetas.',
    ocr_high_speed: 'Alta velocidad',
    ocr_native_pdf: 'PDF nativo',
    ocr_aws: 'AWS Textract',
    ocr_aws_desc: 'Extracción inteligente de texto, tablas y formularios de Amazon.',
    ocr_invoices: 'Facturas',
    ocr_id_docs: 'Documentos ID',
    ocr_complex_tables: 'Tablas complejas',
    ocr_endpoint: 'Endpoint',
    ocr_api_key: 'API Key',
    ocr_credentials_file: 'Archivo de credenciales JSON',
    ocr_project_id: 'Proyecto ID',
    ocr_access_key: 'Access Key ID',
    ocr_secret_key: 'Secret Access Key',
    ocr_region: 'Región',
    ocr_language: 'Idioma',
    ocr_primary_language: 'Idioma principal',
    ocr_secondary_language: 'Idioma secundario (opcional)',
    ocr_none: 'Ninguno',
    ocr_image_processing: 'Procesamiento de Imagen',
    ocr_enhance_contrast: 'Mejorar contraste automáticamente',
    ocr_fix_skew: 'Corregir inclinación',
    ocr_remove_noise: 'Eliminar ruido de fondo',
    ocr_binarize: 'Binarizar imagen (blanco y negro)',
    ocr_structure_detection: 'Detección de Estructuras',
    ocr_detect_tables: 'Detectar tablas',
    ocr_detect_forms: 'Detectar formularios',
    ocr_detect_handwriting: 'Detectar escritura a mano',
    ocr_detect_barcodes: 'Detectar códigos de barras/QR',
    ocr_quality: 'Calidad y Rendimiento',
    ocr_confidence: 'Umbral de confianza',
    ocr_resolution: 'Resolución de procesamiento (DPI)',
    ocr_segmentation: 'Modo de segmentación',
    ocr_seg_auto: 'Automático',
    ocr_seg_block: 'Bloque único de texto',
    ocr_seg_column: 'Columna única',
    ocr_seg_line: 'Línea única',
    ocr_seg_word: 'Palabra única',
    ocr_seg_sparse: 'Texto disperso',
    ocr_test_config: 'Probar configuración',
    ocr_test_desc: 'Sube una imagen de prueba para verificar que el OCR funciona correctamente.',
    ocr_test_btn: 'Probar OCR',
    ocr_ready: 'Listo para usar',
    ocr_verify_update: 'Verificar/Actualizar',
    ocr_create_resource: 'Crear recurso',
    ocr_configure_console: 'Configurar en consola',

    // IA Dashboard
    ai_title: 'Alqvimia IA/ML Center',
    ai_subtitle: 'Automatización Inteligente Empresarial',
    ai_metrics: 'Métricas',
    ai_configuration: 'Configuración',
    ai_overview: 'Overview',
    ai_process_mining: 'Process Mining',
    ai_task_mining: 'Task Mining',
    ai_doc_understanding: 'Document Understanding',
    ai_agentic: 'Agentic Automation',
    ai_comm_mining: 'Communications Mining',
    ai_test_suite: 'Test Suite',
    ai_documents_processed: 'Documentos Procesados',
    ai_processes_discovered: 'Procesos Descubiertos',
    ai_tasks_automated: 'Tareas Automatizadas',
    ai_time_saved: 'Tiempo Ahorrado',
    ai_avg_accuracy: 'Precisión Promedio',
    ai_active_agents: 'Agentes Activos',
    ai_modules: 'Módulos de IA/ML',
    ai_pm_desc: 'Descubre y analiza procesos de negocio',
    ai_tm_desc: 'Identifica tareas automatizables',
    ai_du_desc: 'Extrae datos de documentos con IA',
    ai_aa_desc: 'Agentes autónomos inteligentes',
    ai_cm_desc: 'Analiza emails, chats y llamadas',
    ai_ts_desc: 'Pruebas automatizadas con IA',

    // Process Mining
    pm_title: 'Process Mining',
    pm_subtitle: 'Descubre, analiza y optimiza tus procesos de negocio',
    pm_import_log: 'Importar Log',
    pm_new_analysis: 'Nuevo Análisis',
    pm_variants: 'variantes',
    pm_cases_analyzed: 'Casos analizados',
    pm_avg_time: 'Tiempo promedio',
    pm_bottleneck: 'Cuello de botella',
    pm_view_map: 'Ver Mapa',
    pm_optimize: 'Optimizar',
    pm_visualization: 'Visualización de Procesos',
    pm_select_process: 'Selecciona un proceso para ver su mapa de flujo interactivo',

    // Task Mining
    tm_title: 'Task Mining',
    tm_subtitle: 'Descubre tareas repetitivas candidatas para automatización',
    tm_start_recording: 'Iniciar Grabación',
    tm_analyze_tasks: 'Analizar Tareas',
    tm_detected_task: 'Tarea Detectada',
    tm_frequency: 'Frecuencia/día',
    tm_avg_time: 'Tiempo Prom.',
    tm_automatable: 'Automatizable',
    tm_priority: 'Prioridad',
    tm_action: 'Acción',
    tm_automate: 'Automatizar',
    tm_high: 'Alta',
    tm_medium: 'Media',
    tm_low: 'Baja',
    tm_savings_potential: 'Potencial de Ahorro Estimado',
    tm_hours_month: 'Horas/mes ahorrables',
    tm_savings_month: 'Ahorro estimado/mes',
    tm_roi: 'ROI estimado',

    // Document Understanding
    du_title: 'Document Understanding (IDP)',
    du_subtitle: 'Procesamiento Inteligente de Documentos con Machine Learning',
    du_train_model: 'Entrenar Modelo',
    du_process_docs: 'Procesar Documentos',
    du_invoices: 'Facturas',
    du_contracts: 'Contratos',
    du_purchase_orders: 'Órdenes de Compra',
    du_forms: 'Formularios',
    du_receipts: 'Recibos',
    du_id_documents: 'Documentos ID',
    du_documents: 'documentos',
    du_accuracy: 'precisión',
    du_pipeline: 'Pipeline de Extracción',
    du_digitization: 'Digitalización',
    du_digitization_desc: 'OCR y preprocesamiento',
    du_classification: 'Clasificación',
    du_classification_desc: 'ML clasifica tipo documento',
    du_extraction: 'Extracción',
    du_extraction_desc: 'NER extrae campos clave',
    du_validation: 'Validación',
    du_validation_desc: 'Reglas de negocio y confianza',
    du_export: 'Exportación',
    du_export_desc: 'Integración con sistemas',
    du_extractable_fields: 'Campos Extraíbles (Ejemplo: Factura)',

    // Agentic Automation
    aa_title: 'Agentic Automation',
    aa_subtitle: 'Agentes autónomos inteligentes que trabajan por ti',
    aa_create_agent: 'Crear Nuevo Agente',
    aa_tasks_executed: 'Tareas ejecutadas',
    aa_success_rate: 'Tasa de éxito',
    aa_pause: 'Pausar',
    aa_start: 'Iniciar',
    aa_configure: 'Configurar',
    aa_capabilities: 'Capacidades de los Agentes',
    aa_decision_making: 'Toma de decisiones',
    aa_exception_handling: 'Manejo de excepciones',
    aa_continuous_learning: 'Aprendizaje continuo',
    aa_multi_agent: 'Colaboración multi-agente',
    aa_llm_integration: 'Integración con LLMs',
    aa_self_optimization: 'Auto-optimización',

    // Communications Mining
    cm_title: 'Communications Mining',
    cm_subtitle: 'Analiza emails, chats y llamadas para descubrir insights',
    cm_connect_sources: 'Conectar Fuentes',
    cm_emails: 'Emails',
    cm_chats: 'Chats',
    cm_calls: 'Llamadas',
    cm_sentiment: 'Sentimiento',
    cm_main_topics: 'Temas principales',
    cm_insights: 'Insights Descubiertos',

    // Test Suite
    ts_title: 'Test Suite',
    ts_subtitle: 'Pruebas automatizadas para tus workflows y robots',
    ts_import_tests: 'Importar Tests',
    ts_run_suite: 'Ejecutar Suite',
    ts_total_tests: 'Total Tests',
    ts_passed: 'Pasados',
    ts_failed: 'Fallados',
    ts_skipped: 'Omitidos',
    ts_unit_tests: 'Unit Tests',
    ts_unit_desc: 'Pruebas de acciones individuales',
    ts_integration_tests: 'Integration Tests',
    ts_integration_desc: 'Pruebas de flujos completos',
    ts_e2e_tests: 'E2E Tests',
    ts_e2e_desc: 'Pruebas end-to-end',
    ts_success_rate: 'Tasa de éxito',

    // Code Editor
    ce_title: 'Editor de Código',
    ce_new_file: 'Nuevo archivo',
    ce_save_file: 'Guardar',
    ce_run_code: 'Ejecutar',
    ce_to_workflow: 'A Workflow',
    ce_ai_commands: 'Comando IA',
    ce_voice: 'Voz',
    ce_stop: 'Detener',
    ce_console: 'Consola',
    ce_clear_console: 'Limpiar consola',
    ce_ai_panel: 'Panel de IA',
    ce_explain: 'Explicar',
    ce_optimize: 'Optimizar',
    ce_refactor: 'Refactorizar',
    ce_debug: 'Buscar Bugs',
    ce_document: 'Documentar',
    ce_test: 'Generar Tests',
    ce_convert: 'Convertir',
    ce_security: 'Seguridad',
    ce_complete: 'Completar',
    ce_fix: 'Corregir',
    ce_lines: 'líneas',
    ce_saved: 'Guardado',
    ce_unsaved: 'Sin guardar',
    ce_listening: 'Escuchando...',

    // Ayuda general
    help_title: '¿Cómo funciona?',
    help_close: 'Cerrar ayuda',
    help_got_it: 'Entendido',
    help_learn_more: 'Saber más',
    help_tips: 'Consejos',
    help_shortcuts: 'Atajos de teclado',

    // Ayuda Workflows
    help_wf_step1_title: 'Arrastra acciones',
    help_wf_step1_desc: 'Selecciona acciones del panel izquierdo y arrástralas al área de trabajo.',
    help_wf_step2_title: 'Configura propiedades',
    help_wf_step2_desc: 'Haz clic en cada acción para configurar sus parámetros en el panel derecho.',
    help_wf_step3_title: 'Conecta el flujo',
    help_wf_step3_desc: 'Las acciones se ejecutan en orden de arriba hacia abajo.',
    help_wf_step4_title: 'Guarda y ejecuta',
    help_wf_step4_desc: 'Guarda tu workflow y ejecútalo desde el Ejecutor.',
    help_wf_tip_voice: 'Usa comandos de voz para agregar acciones',
    help_wf_tip_debug: 'Usa F9 para agregar breakpoints',
    help_wf_tip_ai: 'Genera workflows con IA describiendo lo que necesitas',

    // Ayuda Code Editor
    help_ce_step1_title: 'Escribe tu código',
    help_ce_step1_desc: 'Usa el editor con resaltado de sintaxis para escribir código.',
    help_ce_step2_title: 'Usa comandos de IA',
    help_ce_step2_desc: 'Presiona Ctrl+I para invocar asistente de IA.',
    help_ce_step3_title: 'Ejecuta y prueba',
    help_ce_step3_desc: 'Ejecuta tu código y ve los resultados en la consola.',
    help_ce_step4_title: 'Exporta a Workflow',
    help_ce_step4_desc: 'Convierte tu código en acciones de workflow.',
    help_ce_tip_ai: 'La IA puede explicar, optimizar y refactorizar código',
    help_ce_tip_voice: 'Dicta código usando comandos de voz',

    // Ayuda AI Dashboard
    help_ai_step1_title: 'Explora los módulos',
    help_ai_step1_desc: 'Selecciona entre Process Mining, Task Mining, IDP y más.',
    help_ai_step2_title: 'Analiza datos',
    help_ai_step2_desc: 'Importa logs y documentos para análisis con IA.',
    help_ai_step3_title: 'Descubre insights',
    help_ai_step3_desc: 'La IA identifica patrones, cuellos de botella y oportunidades.',
    help_ai_step4_title: 'Automatiza',
    help_ai_step4_desc: 'Convierte los insights en workflows automatizados.',
    help_ai_tip_pm: 'Process Mining descubre procesos reales de tus datos',
    help_ai_tip_idp: 'IDP extrae datos de facturas, contratos y más',

    // Ayuda Recorder
    help_rec_step1_title: 'Inicia grabación',
    help_rec_step1_desc: 'Haz clic en Grabar para comenzar a capturar tus acciones.',
    help_rec_step2_title: 'Realiza las acciones',
    help_rec_step2_desc: 'Navega y ejecuta las acciones que deseas automatizar.',
    help_rec_step3_title: 'Detén y revisa',
    help_rec_step3_desc: 'Detén la grabación y revisa los pasos capturados.',
    help_rec_step4_title: 'Genera workflow',
    help_rec_step4_desc: 'Convierte la grabación en un workflow ejecutable.',

    // Ayuda Settings
    help_set_step1_title: 'Personaliza tu experiencia',
    help_set_step1_desc: 'Cambia tema, idioma y preferencias visuales.',
    help_set_step2_title: 'Configura integraciones',
    help_set_step2_desc: 'Conecta con servicios externos como IA, OCR y más.',
    help_set_step3_title: 'Gestiona credenciales',
    help_set_step3_desc: 'Almacena de forma segura tus credenciales.',

    // Mensajes
    msg_success: 'Éxito',
    msg_error: 'Error',
    msg_warning: 'Advertencia',
    msg_info: 'Información',
    msg_loading: 'Cargando...',
    msg_saving: 'Guardando...',
    msg_saved: 'Guardado exitosamente',
    msg_deleted: 'Eliminado exitosamente',
    msg_copied: 'Copiado al portapapeles',
    msg_no_data: 'No hay datos disponibles',
    msg_confirm_delete: '¿Estás seguro de que deseas eliminar?',
    msg_unsaved_changes: 'Tienes cambios sin guardar. ¿Deseas continuar?',

    // Idiomas
    lang_spanish: 'Español',
    lang_english: 'English',
    lang_portuguese: 'Português',
    lang_select: 'Seleccionar idioma',

    // Recorder
    rec_connect_first: 'Conecta al servidor primero',
    rec_select_window: 'Por favor selecciona una ventana para grabar',
    rec_target_window: 'Ventana Objetivo',
    rec_no_window: 'No se ha seleccionado ninguna ventana. Se grabará en cualquier ventana activa.',
    rec_no_windows: 'No se encontraron ventanas abiertas',
    rec_start_recording: 'Iniciar Grabación',
    rec_stop_recording: 'Detener',
    rec_pause: 'Pausar',
    rec_resume: 'Reanudar',
    rec_capture_element: 'Capturar Elemento',
    rec_recorded_actions: 'Acciones Grabadas',
    rec_no_actions: 'No hay acciones grabadas',
    rec_save_workflow: 'Guardar como Workflow',
    rec_clear_recording: 'Limpiar',
    rec_select_window_modal: 'Seleccionar Ventana para Grabar',
    rec_update_list: 'Actualizar Lista',
    rec_windows_found: 'ventanas encontradas',
    rec_searching_windows: 'Buscando ventanas abiertas...',
    rec_no_windows_found: 'No se encontraron ventanas abiertas',
    rec_open_app_refresh: 'Abre alguna aplicación y actualiza la lista',
    rec_configure_element: 'Configurar Elemento Capturado',
    rec_element_info: 'Información del Elemento',
    rec_action_config: 'Configuración de Acción',
    rec_variable_name: 'Nombre de Variable',
    rec_element_type: 'Tipo de Elemento',
    rec_action_type: 'Tipo de Acción',
    rec_wait_before: 'Espera antes (ms)',
    rec_wait_after: 'Espera después (ms)',
    rec_capture_image: 'Capturar imagen del elemento',
    rec_description: 'Descripción (opcional)',
    rec_add_action: 'Agregar Acción',
    rec_workflow_name: 'Nombre del Workflow',
    rec_workflow_desc: 'Descripción',
    rec_summary: 'Resumen',
    rec_actions_count: 'acciones'
  },

  en: {
    // General
    app_name: 'Alqvimia',
    version: 'v2.0',
    connected: 'Connected',
    disconnected: 'Disconnected',
    server_active: 'Server active',
    click_to_connect: 'Click to connect',
    expand_menu: 'Expand menu',
    collapse_menu: 'Collapse menu',

    // Navigation
    nav_spy: 'Element Spy',
    nav_recorder: 'Recorder',
    nav_workflows: 'Workflows',
    nav_executor: 'Executor',
    nav_code_editor: 'Code Editor',
    nav_agents: 'Agents',
    nav_mcp: 'MCP Connectors',
    nav_marketplace: 'Marketplace',
    nav_library: 'Library',
    nav_ai_dashboard: 'AI Dashboard',
    nav_omnichannel: 'Omnichannel',
    nav_videoconference: 'Video Conference',
    nav_settings: 'Settings',
    nav_scheduler: 'Scheduler',
    nav_onboarding: 'Wizard',
    nav_admin: 'Admin',

    // Scheduler
    scheduler_subtitle: 'Schedule automatic workflow executions',
    scheduler_new: 'New Schedule',
    scheduler_active: 'Active',
    scheduler_paused: 'Paused',

    // Common buttons
    btn_save: 'Save',
    btn_cancel: 'Cancel',
    btn_delete: 'Delete',
    btn_edit: 'Edit',
    btn_new: 'New',
    btn_import: 'Import',
    btn_export: 'Export',
    btn_close: 'Close',
    btn_confirm: 'Confirm',
    btn_search: 'Search',
    btn_filter: 'Filter',
    btn_refresh: 'Refresh',
    btn_run: 'Run',
    btn_stop: 'Stop',
    btn_pause: 'Pause',
    btn_continue: 'Continue',
    btn_copy: 'Copy',
    btn_paste: 'Paste',
    btn_duplicate: 'Duplicate',
    btn_download: 'Download',
    btn_upload: 'Upload',
    btn_help: 'Help',
    btn_settings: 'Settings',
    btn_back: 'Back',
    btn_next: 'Next',
    btn_previous: 'Previous',
    btn_apply: 'Apply',
    btn_reset: 'Reset',
    btn_test: 'Test',
    btn_add: 'Add',
    btn_remove: 'Remove',
    btn_select: 'Select',
    btn_select_all: 'Select all',
    btn_clear: 'Clear',
    btn_view: 'View',
    btn_preview: 'Preview',

    // Element Spy
    spy_title: 'Element Spy',
    spy_subtitle: 'Inspect and capture web element selectors',
    spy_help_title: 'How does Element Spy work?',
    spy_help_intro: 'Element Spy allows you to inspect web pages and capture element selectors to use in your automations.',
    spy_how_to_use: 'How to use?',
    spy_step_1: 'Enter the URL of the page you want to inspect',
    spy_step_2: 'Select the operation mode',
    spy_step_3: 'Click on elements to capture their selectors',
    spy_step_4: 'Copy your preferred selector to use in your workflows',
    spy_modes: 'Operation Modes',
    spy_mode_iframe: 'Iframe Mode',
    spy_mode_iframe_desc: 'Loads the page within Alqvimia. Works without plugins.',
    spy_mode_iframe_features: 'No installation|Fast|Limited by CORS',
    spy_mode_bookmarklet: 'Bookmarklet',
    spy_mode_bookmarklet_desc: 'Drag the button to your bookmarks and use it on any site.',
    spy_mode_bookmarklet_features: 'Works on any site|No CORS limits|Requires dragging',
    spy_mode_extension: 'Extension',
    spy_mode_extension_desc: 'Install the extension for full functionality.',
    spy_mode_extension_features: 'Full functionality|Advanced recording|Requires installation',
    spy_url_label: 'URL to inspect',
    spy_url_placeholder: 'https://example.com',
    spy_load_page: 'Load Page',
    spy_highlight_color: 'Highlight color',
    spy_inspector_title: 'Element Inspector',
    spy_no_element: 'Click on an element on the page to inspect it',
    spy_element_tag: 'Tag',
    spy_element_id: 'ID',
    spy_element_class: 'Class',
    spy_element_name: 'Name',
    spy_element_text: 'Text',
    spy_element_xpath: 'XPath',
    spy_selector_options: 'Selector Options',
    spy_copy_selector: 'Copy',
    spy_add_to_workflow: 'Add to Workflow',
    spy_recent_elements: 'Recent Elements',
    spy_drag_bookmarklet: 'Drag this button to your bookmarks bar',

    // Workflows
    wf_title: 'Workflow Studio',
    wf_new: 'New',
    wf_save: 'Save',
    wf_import: 'Import',
    wf_export: 'Export',
    wf_migrate: 'Migrate',
    wf_ai_generate: 'AI',
    wf_code_editor: 'Editor',
    wf_debug: 'Debug',
    wf_actions: 'Actions',
    wf_properties: 'Properties',
    wf_variables: 'Variables',
    wf_search_actions: 'Search actions...',
    wf_drag_here: 'Drag actions here to build your workflow',
    wf_use_ai: 'Or use the AI generator to create workflows automatically',
    wf_start: 'Start',
    wf_end: 'End',
    wf_steps: 'steps',
    wf_breakpoints: 'breakpoints',
    wf_clipboard: 'Clipboard',
    wf_debugging: 'Debugging...',
    wf_list_view: 'List view',
    wf_flow_view: 'Flow view',
    wf_voice_commands: 'Voice commands',
    wf_stop_voice: 'Stop',
    wf_load_more_actions: 'Load more actions',

    // Save Workflow
    wf_save_title: 'Save Workflow',
    wf_save_name: 'Workflow Name',
    wf_save_location: 'Save Location',
    wf_save_local: 'Local Storage',
    wf_save_local_desc: 'Saved in browser',
    wf_save_file: 'Download File',
    wf_save_file_desc: '.alq file on your PC',
    wf_save_folder: 'Destination Folder',
    wf_save_new_folder: 'New Folder',
    wf_save_folder_name: 'New folder name...',
    wf_save_summary: 'Summary',
    wf_save_will_save: 'Will be saved to:',
    wf_folder_my_workflows: 'My Workflows',
    wf_folder_production: 'Production',
    wf_folder_development: 'Development',
    wf_folder_testing: 'Testing',
    wf_folder_templates: 'Templates',
    wf_folder_archived: 'Archived',

    // Action categories
    cat_control_flow: 'Control Flow',
    cat_dialogs: 'Dialogs and Messages',
    cat_variables: 'Variables and Data',
    cat_text: 'Text and Strings',
    cat_collections: 'Collections',
    cat_web_browser: 'Web Browser',
    cat_active_directory: 'Active Directory',
    cat_ai: 'Artificial Intelligence',
    cat_database: 'Database',
    cat_files: 'Files and Folders',
    cat_email: 'Email',
    cat_excel: 'Excel',
    cat_pdf: 'PDF',
    cat_rest: 'REST / API',
    cat_sap: 'SAP',
    cat_microsoft365: 'Microsoft 365',
    cat_mouse_keyboard: 'Mouse & Keyboard',
    cat_windows: 'Windows / System',
    cat_ocr_image: 'OCR and Images',
    cat_credentials: 'Credentials',

    // OCR Settings
    ocr_title: 'OCR Configuration',
    ocr_subtitle: 'Configure optical character recognition providers. Select an engine and set up credentials.',
    ocr_tesseract: 'Tesseract OCR',
    ocr_tesseract_desc: 'Open source OCR engine. Works offline.',
    ocr_free: 'FREE',
    ocr_cloud: 'CLOUD',
    ocr_offline: 'Offline',
    ocr_languages: 'languages',
    ocr_open_source: 'Open Source',
    ocr_azure: 'Azure Computer Vision',
    ocr_azure_desc: 'Microsoft enterprise OCR with advanced AI and high accuracy.',
    ocr_advanced_ai: 'Advanced AI',
    ocr_tables_forms: 'Tables/Forms',
    ocr_handwriting: 'Handwriting',
    ocr_google: 'Google Cloud Vision',
    ocr_google_desc: 'Powerful Google OCR with object and label detection.',
    ocr_high_speed: 'High speed',
    ocr_native_pdf: 'Native PDF',
    ocr_aws: 'AWS Textract',
    ocr_aws_desc: 'Intelligent text, table and form extraction from Amazon.',
    ocr_invoices: 'Invoices',
    ocr_id_docs: 'ID Documents',
    ocr_complex_tables: 'Complex tables',
    ocr_endpoint: 'Endpoint',
    ocr_api_key: 'API Key',
    ocr_credentials_file: 'JSON credentials file',
    ocr_project_id: 'Project ID',
    ocr_access_key: 'Access Key ID',
    ocr_secret_key: 'Secret Access Key',
    ocr_region: 'Region',
    ocr_language: 'Language',
    ocr_primary_language: 'Primary language',
    ocr_secondary_language: 'Secondary language (optional)',
    ocr_none: 'None',
    ocr_image_processing: 'Image Processing',
    ocr_enhance_contrast: 'Auto-enhance contrast',
    ocr_fix_skew: 'Fix skew',
    ocr_remove_noise: 'Remove background noise',
    ocr_binarize: 'Binarize image (black and white)',
    ocr_structure_detection: 'Structure Detection',
    ocr_detect_tables: 'Detect tables',
    ocr_detect_forms: 'Detect forms',
    ocr_detect_handwriting: 'Detect handwriting',
    ocr_detect_barcodes: 'Detect barcodes/QR',
    ocr_quality: 'Quality and Performance',
    ocr_confidence: 'Confidence threshold',
    ocr_resolution: 'Processing resolution (DPI)',
    ocr_segmentation: 'Segmentation mode',
    ocr_seg_auto: 'Automatic',
    ocr_seg_block: 'Single text block',
    ocr_seg_column: 'Single column',
    ocr_seg_line: 'Single line',
    ocr_seg_word: 'Single word',
    ocr_seg_sparse: 'Sparse text',
    ocr_test_config: 'Test configuration',
    ocr_test_desc: 'Upload a test image to verify OCR works correctly.',
    ocr_test_btn: 'Test OCR',
    ocr_ready: 'Ready to use',
    ocr_verify_update: 'Verify/Update',
    ocr_create_resource: 'Create resource',
    ocr_configure_console: 'Configure in console',

    // AI Dashboard
    ai_title: 'Alqvimia AI/ML Center',
    ai_subtitle: 'Enterprise Intelligent Automation',
    ai_metrics: 'Metrics',
    ai_configuration: 'Configuration',
    ai_overview: 'Overview',
    ai_process_mining: 'Process Mining',
    ai_task_mining: 'Task Mining',
    ai_doc_understanding: 'Document Understanding',
    ai_agentic: 'Agentic Automation',
    ai_comm_mining: 'Communications Mining',
    ai_test_suite: 'Test Suite',
    ai_documents_processed: 'Documents Processed',
    ai_processes_discovered: 'Processes Discovered',
    ai_tasks_automated: 'Tasks Automated',
    ai_time_saved: 'Time Saved',
    ai_avg_accuracy: 'Average Accuracy',
    ai_active_agents: 'Active Agents',
    ai_modules: 'AI/ML Modules',
    ai_pm_desc: 'Discover and analyze business processes',
    ai_tm_desc: 'Identify automatable tasks',
    ai_du_desc: 'Extract data from documents with AI',
    ai_aa_desc: 'Intelligent autonomous agents',
    ai_cm_desc: 'Analyze emails, chats and calls',
    ai_ts_desc: 'AI-powered automated testing',

    // Process Mining
    pm_title: 'Process Mining',
    pm_subtitle: 'Discover, analyze and optimize your business processes',
    pm_import_log: 'Import Log',
    pm_new_analysis: 'New Analysis',
    pm_variants: 'variants',
    pm_cases_analyzed: 'Cases analyzed',
    pm_avg_time: 'Average time',
    pm_bottleneck: 'Bottleneck',
    pm_view_map: 'View Map',
    pm_optimize: 'Optimize',
    pm_visualization: 'Process Visualization',
    pm_select_process: 'Select a process to view its interactive flow map',

    // Task Mining
    tm_title: 'Task Mining',
    tm_subtitle: 'Discover repetitive tasks candidates for automation',
    tm_start_recording: 'Start Recording',
    tm_analyze_tasks: 'Analyze Tasks',
    tm_detected_task: 'Detected Task',
    tm_frequency: 'Frequency/day',
    tm_avg_time: 'Avg Time',
    tm_automatable: 'Automatable',
    tm_priority: 'Priority',
    tm_action: 'Action',
    tm_automate: 'Automate',
    tm_high: 'High',
    tm_medium: 'Medium',
    tm_low: 'Low',
    tm_savings_potential: 'Estimated Savings Potential',
    tm_hours_month: 'Hours/month saveable',
    tm_savings_month: 'Estimated savings/month',
    tm_roi: 'Estimated ROI',

    // Document Understanding
    du_title: 'Document Understanding (IDP)',
    du_subtitle: 'Intelligent Document Processing with Machine Learning',
    du_train_model: 'Train Model',
    du_process_docs: 'Process Documents',
    du_invoices: 'Invoices',
    du_contracts: 'Contracts',
    du_purchase_orders: 'Purchase Orders',
    du_forms: 'Forms',
    du_receipts: 'Receipts',
    du_id_documents: 'ID Documents',
    du_documents: 'documents',
    du_accuracy: 'accuracy',
    du_pipeline: 'Extraction Pipeline',
    du_digitization: 'Digitization',
    du_digitization_desc: 'OCR and preprocessing',
    du_classification: 'Classification',
    du_classification_desc: 'ML classifies document type',
    du_extraction: 'Extraction',
    du_extraction_desc: 'NER extracts key fields',
    du_validation: 'Validation',
    du_validation_desc: 'Business rules and confidence',
    du_export: 'Export',
    du_export_desc: 'System integration',
    du_extractable_fields: 'Extractable Fields (Example: Invoice)',

    // Agentic Automation
    aa_title: 'Agentic Automation',
    aa_subtitle: 'Intelligent autonomous agents that work for you',
    aa_create_agent: 'Create New Agent',
    aa_tasks_executed: 'Tasks executed',
    aa_success_rate: 'Success rate',
    aa_pause: 'Pause',
    aa_start: 'Start',
    aa_configure: 'Configure',
    aa_capabilities: 'Agent Capabilities',
    aa_decision_making: 'Decision making',
    aa_exception_handling: 'Exception handling',
    aa_continuous_learning: 'Continuous learning',
    aa_multi_agent: 'Multi-agent collaboration',
    aa_llm_integration: 'LLM integration',
    aa_self_optimization: 'Self-optimization',

    // Communications Mining
    cm_title: 'Communications Mining',
    cm_subtitle: 'Analyze emails, chats and calls to discover insights',
    cm_connect_sources: 'Connect Sources',
    cm_emails: 'Emails',
    cm_chats: 'Chats',
    cm_calls: 'Calls',
    cm_sentiment: 'Sentiment',
    cm_main_topics: 'Main topics',
    cm_insights: 'Discovered Insights',

    // Test Suite
    ts_title: 'Test Suite',
    ts_subtitle: 'Automated testing for your workflows and robots',
    ts_import_tests: 'Import Tests',
    ts_run_suite: 'Run Suite',
    ts_total_tests: 'Total Tests',
    ts_passed: 'Passed',
    ts_failed: 'Failed',
    ts_skipped: 'Skipped',
    ts_unit_tests: 'Unit Tests',
    ts_unit_desc: 'Individual action tests',
    ts_integration_tests: 'Integration Tests',
    ts_integration_desc: 'Complete flow tests',
    ts_e2e_tests: 'E2E Tests',
    ts_e2e_desc: 'End-to-end tests',
    ts_success_rate: 'Success rate',

    // Code Editor
    ce_title: 'Code Editor',
    ce_new_file: 'New file',
    ce_save_file: 'Save',
    ce_run_code: 'Run',
    ce_to_workflow: 'To Workflow',
    ce_ai_commands: 'AI Command',
    ce_voice: 'Voice',
    ce_stop: 'Stop',
    ce_console: 'Console',
    ce_clear_console: 'Clear console',
    ce_ai_panel: 'AI Panel',
    ce_explain: 'Explain',
    ce_optimize: 'Optimize',
    ce_refactor: 'Refactor',
    ce_debug: 'Find Bugs',
    ce_document: 'Document',
    ce_test: 'Generate Tests',
    ce_convert: 'Convert',
    ce_security: 'Security',
    ce_complete: 'Complete',
    ce_fix: 'Fix',
    ce_lines: 'lines',
    ce_saved: 'Saved',
    ce_unsaved: 'Unsaved',
    ce_listening: 'Listening...',

    // General Help
    help_title: 'How does it work?',
    help_close: 'Close help',
    help_got_it: 'Got it',
    help_learn_more: 'Learn more',
    help_tips: 'Tips',
    help_shortcuts: 'Keyboard shortcuts',

    // Workflows Help
    help_wf_step1_title: 'Drag actions',
    help_wf_step1_desc: 'Select actions from the left panel and drag them to the workspace.',
    help_wf_step2_title: 'Configure properties',
    help_wf_step2_desc: 'Click on each action to configure its parameters in the right panel.',
    help_wf_step3_title: 'Connect the flow',
    help_wf_step3_desc: 'Actions are executed in order from top to bottom.',
    help_wf_step4_title: 'Save and execute',
    help_wf_step4_desc: 'Save your workflow and run it from the Executor.',
    help_wf_tip_voice: 'Use voice commands to add actions',
    help_wf_tip_debug: 'Use F9 to add breakpoints',
    help_wf_tip_ai: 'Generate workflows with AI by describing what you need',

    // Code Editor Help
    help_ce_step1_title: 'Write your code',
    help_ce_step1_desc: 'Use the syntax-highlighted editor to write code.',
    help_ce_step2_title: 'Use AI commands',
    help_ce_step2_desc: 'Press Ctrl+I to invoke the AI assistant.',
    help_ce_step3_title: 'Run and test',
    help_ce_step3_desc: 'Execute your code and see results in the console.',
    help_ce_step4_title: 'Export to Workflow',
    help_ce_step4_desc: 'Convert your code into workflow actions.',
    help_ce_tip_ai: 'AI can explain, optimize and refactor code',
    help_ce_tip_voice: 'Dictate code using voice commands',

    // AI Dashboard Help
    help_ai_step1_title: 'Explore the modules',
    help_ai_step1_desc: 'Select from Process Mining, Task Mining, IDP and more.',
    help_ai_step2_title: 'Analyze data',
    help_ai_step2_desc: 'Import logs and documents for AI analysis.',
    help_ai_step3_title: 'Discover insights',
    help_ai_step3_desc: 'AI identifies patterns, bottlenecks and opportunities.',
    help_ai_step4_title: 'Automate',
    help_ai_step4_desc: 'Convert insights into automated workflows.',
    help_ai_tip_pm: 'Process Mining discovers real processes from your data',
    help_ai_tip_idp: 'IDP extracts data from invoices, contracts and more',

    // Recorder Help
    help_rec_step1_title: 'Start recording',
    help_rec_step1_desc: 'Click Record to start capturing your actions.',
    help_rec_step2_title: 'Perform the actions',
    help_rec_step2_desc: 'Navigate and execute the actions you want to automate.',
    help_rec_step3_title: 'Stop and review',
    help_rec_step3_desc: 'Stop the recording and review the captured steps.',
    help_rec_step4_title: 'Generate workflow',
    help_rec_step4_desc: 'Convert the recording into an executable workflow.',

    // Settings Help
    help_set_step1_title: 'Customize your experience',
    help_set_step1_desc: 'Change theme, language and visual preferences.',
    help_set_step2_title: 'Configure integrations',
    help_set_step2_desc: 'Connect with external services like AI, OCR and more.',
    help_set_step3_title: 'Manage credentials',
    help_set_step3_desc: 'Securely store your credentials.',

    // Messages
    msg_success: 'Success',
    msg_error: 'Error',
    msg_warning: 'Warning',
    msg_info: 'Information',
    msg_loading: 'Loading...',
    msg_saving: 'Saving...',
    msg_saved: 'Saved successfully',
    msg_deleted: 'Deleted successfully',
    msg_copied: 'Copied to clipboard',
    msg_no_data: 'No data available',
    msg_confirm_delete: 'Are you sure you want to delete?',
    msg_unsaved_changes: 'You have unsaved changes. Do you want to continue?',

    // Languages
    lang_spanish: 'Español',
    lang_english: 'English',
    lang_portuguese: 'Português',
    lang_select: 'Select language',

    // Recorder
    rec_connect_first: 'Connect to server first',
    rec_select_window: 'Please select a window to record',
    rec_target_window: 'Target Window',
    rec_no_window: 'No window selected. Will record on any active window.',
    rec_no_windows: 'No open windows found',
    rec_start_recording: 'Start Recording',
    rec_stop_recording: 'Stop',
    rec_pause: 'Pause',
    rec_resume: 'Resume',
    rec_capture_element: 'Capture Element',
    rec_recorded_actions: 'Recorded Actions',
    rec_no_actions: 'No recorded actions',
    rec_save_workflow: 'Save as Workflow',
    rec_clear_recording: 'Clear',
    rec_select_window_modal: 'Select Window to Record',
    rec_update_list: 'Update List',
    rec_windows_found: 'windows found',
    rec_searching_windows: 'Searching for open windows...',
    rec_no_windows_found: 'No open windows found',
    rec_open_app_refresh: 'Open an application and refresh the list',
    rec_configure_element: 'Configure Captured Element',
    rec_element_info: 'Element Information',
    rec_action_config: 'Action Configuration',
    rec_variable_name: 'Variable Name',
    rec_element_type: 'Element Type',
    rec_action_type: 'Action Type',
    rec_wait_before: 'Wait before (ms)',
    rec_wait_after: 'Wait after (ms)',
    rec_capture_image: 'Capture element image',
    rec_description: 'Description (optional)',
    rec_add_action: 'Add Action',
    rec_workflow_name: 'Workflow Name',
    rec_workflow_desc: 'Description',
    rec_summary: 'Summary',
    rec_actions_count: 'actions'
  },

  pt: {
    // General
    app_name: 'Alqvimia',
    version: 'v2.0',
    connected: 'Conectado',
    disconnected: 'Desconectado',
    server_active: 'Servidor ativo',
    click_to_connect: 'Clique para conectar',
    expand_menu: 'Expandir menu',
    collapse_menu: 'Recolher menu',

    // Navegação
    nav_spy: 'Element Spy',
    nav_recorder: 'Gravador',
    nav_workflows: 'Workflows',
    nav_executor: 'Executor',
    nav_code_editor: 'Editor de Código',
    nav_agents: 'Agentes',
    nav_mcp: 'Conectores MCP',
    nav_marketplace: 'Marketplace',
    nav_library: 'Biblioteca',
    nav_ai_dashboard: 'Painel de IA',
    nav_omnichannel: 'Omnicanalidade',
    nav_videoconference: 'Videoconferência',
    nav_settings: 'Configurações',
    nav_scheduler: 'Agendador',

    // Scheduler
    scheduler_subtitle: 'Agende execuções automáticas de seus workflows',
    scheduler_new: 'Novo Agendamento',
    scheduler_active: 'Ativos',
    scheduler_paused: 'Pausados',

    // Botões comuns
    btn_save: 'Salvar',
    btn_cancel: 'Cancelar',
    btn_delete: 'Excluir',
    btn_edit: 'Editar',
    btn_new: 'Novo',
    btn_import: 'Importar',
    btn_export: 'Exportar',
    btn_close: 'Fechar',
    btn_confirm: 'Confirmar',
    btn_search: 'Buscar',
    btn_filter: 'Filtrar',
    btn_refresh: 'Atualizar',
    btn_run: 'Executar',
    btn_stop: 'Parar',
    btn_pause: 'Pausar',
    btn_continue: 'Continuar',
    btn_copy: 'Copiar',
    btn_paste: 'Colar',
    btn_duplicate: 'Duplicar',
    btn_download: 'Baixar',
    btn_upload: 'Enviar',
    btn_help: 'Ajuda',
    btn_settings: 'Configurações',
    btn_back: 'Voltar',
    btn_next: 'Próximo',
    btn_previous: 'Anterior',
    btn_apply: 'Aplicar',
    btn_reset: 'Redefinir',
    btn_test: 'Testar',
    btn_add: 'Adicionar',
    btn_remove: 'Remover',
    btn_select: 'Selecionar',
    btn_select_all: 'Selecionar tudo',
    btn_clear: 'Limpar',
    btn_view: 'Ver',
    btn_preview: 'Pré-visualizar',

    // Element Spy
    spy_title: 'Element Spy',
    spy_subtitle: 'Inspecione e capture seletores de elementos web',
    spy_help_title: 'Como funciona o Element Spy?',
    spy_help_intro: 'O Element Spy permite inspecionar páginas web e capturar seletores de elementos para usar em suas automações.',
    spy_how_to_use: 'Como usar?',
    spy_step_1: 'Digite a URL da página que deseja inspecionar',
    spy_step_2: 'Selecione o modo de operação',
    spy_step_3: 'Clique nos elementos para capturar seus seletores',
    spy_step_4: 'Copie o seletor de sua preferência para usar em seus workflows',
    spy_modes: 'Modos de Operação',
    spy_mode_iframe: 'Modo Iframe',
    spy_mode_iframe_desc: 'Carrega a página dentro do Alqvimia. Funciona sem plugins.',
    spy_mode_iframe_features: 'Sem instalação|Rápido|Limitado por CORS',
    spy_mode_bookmarklet: 'Bookmarklet',
    spy_mode_bookmarklet_desc: 'Arraste o botão para seus favoritos e use em qualquer site.',
    spy_mode_bookmarklet_features: 'Funciona em qualquer site|Sem limites CORS|Requer arrastar',
    spy_mode_extension: 'Extensão',
    spy_mode_extension_desc: 'Instale a extensão para funcionalidade completa.',
    spy_mode_extension_features: 'Funcionalidade completa|Gravação avançada|Requer instalação',
    spy_url_label: 'URL para inspecionar',
    spy_url_placeholder: 'https://exemplo.com',
    spy_load_page: 'Carregar Página',
    spy_highlight_color: 'Cor de destaque',
    spy_inspector_title: 'Inspetor de Elementos',
    spy_no_element: 'Clique em um elemento na página para inspecioná-lo',
    spy_element_tag: 'Tag',
    spy_element_id: 'ID',
    spy_element_class: 'Classe',
    spy_element_name: 'Nome',
    spy_element_text: 'Texto',
    spy_element_xpath: 'XPath',
    spy_selector_options: 'Opções de Seletor',
    spy_copy_selector: 'Copiar',
    spy_add_to_workflow: 'Adicionar ao Workflow',
    spy_recent_elements: 'Elementos Recentes',
    spy_drag_bookmarklet: 'Arraste este botão para sua barra de favoritos',

    // Workflows
    wf_title: 'Workflow Studio',
    wf_new: 'Novo',
    wf_save: 'Salvar',
    wf_import: 'Importar',
    wf_export: 'Exportar',
    wf_migrate: 'Migrar',
    wf_ai_generate: 'IA',
    wf_code_editor: 'Editor',
    wf_debug: 'Debug',
    wf_actions: 'Ações',
    wf_properties: 'Propriedades',
    wf_variables: 'Variáveis',
    wf_search_actions: 'Buscar ações...',
    wf_drag_here: 'Arraste ações aqui para construir seu workflow',
    wf_use_ai: 'Ou use o gerador com IA para criar workflows automaticamente',
    wf_start: 'Iniciar',
    wf_end: 'Fim',
    wf_steps: 'passos',
    wf_breakpoints: 'breakpoints',
    wf_clipboard: 'Área de transferência',
    wf_debugging: 'Depurando...',
    wf_list_view: 'Vista de lista',
    wf_flow_view: 'Vista de fluxo',
    wf_voice_commands: 'Comandos de voz',
    wf_stop_voice: 'Parar',
    wf_load_more_actions: 'Carregar mais ações',

    // Salvar Workflow
    wf_save_title: 'Salvar Workflow',
    wf_save_name: 'Nome do Workflow',
    wf_save_location: 'Local de Salvamento',
    wf_save_local: 'Armazenamento Local',
    wf_save_local_desc: 'Salvo no navegador',
    wf_save_file: 'Baixar Arquivo',
    wf_save_file_desc: 'Arquivo .alq no seu PC',
    wf_save_folder: 'Pasta de Destino',
    wf_save_new_folder: 'Nova Pasta',
    wf_save_folder_name: 'Nome da nova pasta...',
    wf_save_summary: 'Resumo',
    wf_save_will_save: 'Será salvo em:',
    wf_folder_my_workflows: 'Meus Workflows',
    wf_folder_production: 'Produção',
    wf_folder_development: 'Desenvolvimento',
    wf_folder_testing: 'Testes',
    wf_folder_templates: 'Modelos',
    wf_folder_archived: 'Arquivados',

    // Categorias de ações
    cat_control_flow: 'Controle de Fluxo',
    cat_dialogs: 'Diálogos e Mensagens',
    cat_variables: 'Variáveis e Dados',
    cat_text: 'Texto e Strings',
    cat_collections: 'Coleções',
    cat_web_browser: 'Navegador Web',
    cat_active_directory: 'Active Directory',
    cat_ai: 'Inteligência Artificial',
    cat_database: 'Banco de Dados',
    cat_files: 'Arquivos e Pastas',
    cat_email: 'E-mail',
    cat_excel: 'Excel',
    cat_pdf: 'PDF',
    cat_rest: 'REST / API',
    cat_sap: 'SAP',
    cat_microsoft365: 'Microsoft 365',
    cat_mouse_keyboard: 'Mouse e Teclado',
    cat_windows: 'Windows / Sistema',
    cat_ocr_image: 'OCR e Imagens',
    cat_credentials: 'Credenciais',

    // Configurações OCR
    ocr_title: 'Configuração de OCR',
    ocr_subtitle: 'Configure provedores de reconhecimento óptico de caracteres. Selecione um motor e configure credenciais.',
    ocr_tesseract: 'Tesseract OCR',
    ocr_tesseract_desc: 'Motor OCR de código aberto. Funciona offline.',
    ocr_free: 'GRATUITO',
    ocr_cloud: 'NUVEM',
    ocr_offline: 'Offline',
    ocr_languages: 'idiomas',
    ocr_open_source: 'Código Aberto',
    ocr_azure: 'Azure Computer Vision',
    ocr_azure_desc: 'OCR empresarial da Microsoft com IA avançada e alta precisão.',
    ocr_advanced_ai: 'IA Avançada',
    ocr_tables_forms: 'Tabelas/Forms',
    ocr_handwriting: 'Escrita manual',
    ocr_google: 'Google Cloud Vision',
    ocr_google_desc: 'OCR poderoso do Google com detecção de objetos e etiquetas.',
    ocr_high_speed: 'Alta velocidade',
    ocr_native_pdf: 'PDF nativo',
    ocr_aws: 'AWS Textract',
    ocr_aws_desc: 'Extração inteligente de texto, tabelas e formulários da Amazon.',
    ocr_invoices: 'Faturas',
    ocr_id_docs: 'Documentos de ID',
    ocr_complex_tables: 'Tabelas complexas',
    ocr_endpoint: 'Endpoint',
    ocr_api_key: 'Chave de API',
    ocr_credentials_file: 'Arquivo de credenciais JSON',
    ocr_project_id: 'ID do Projeto',
    ocr_access_key: 'Access Key ID',
    ocr_secret_key: 'Secret Access Key',
    ocr_region: 'Região',
    ocr_language: 'Idioma',
    ocr_primary_language: 'Idioma principal',
    ocr_secondary_language: 'Idioma secundário (opcional)',
    ocr_none: 'Nenhum',
    ocr_image_processing: 'Processamento de Imagem',
    ocr_enhance_contrast: 'Melhorar contraste automaticamente',
    ocr_fix_skew: 'Corrigir inclinação',
    ocr_remove_noise: 'Remover ruído de fundo',
    ocr_binarize: 'Binarizar imagem (preto e branco)',
    ocr_structure_detection: 'Detecção de Estruturas',
    ocr_detect_tables: 'Detectar tabelas',
    ocr_detect_forms: 'Detectar formulários',
    ocr_detect_handwriting: 'Detectar escrita manual',
    ocr_detect_barcodes: 'Detectar códigos de barras/QR',
    ocr_quality: 'Qualidade e Desempenho',
    ocr_confidence: 'Limite de confiança',
    ocr_resolution: 'Resolução de processamento (DPI)',
    ocr_segmentation: 'Modo de segmentação',
    ocr_seg_auto: 'Automático',
    ocr_seg_block: 'Bloco único de texto',
    ocr_seg_column: 'Coluna única',
    ocr_seg_line: 'Linha única',
    ocr_seg_word: 'Palavra única',
    ocr_seg_sparse: 'Texto esparso',
    ocr_test_config: 'Testar configuração',
    ocr_test_desc: 'Envie uma imagem de teste para verificar se o OCR funciona corretamente.',
    ocr_test_btn: 'Testar OCR',
    ocr_ready: 'Pronto para usar',
    ocr_verify_update: 'Verificar/Atualizar',
    ocr_create_resource: 'Criar recurso',
    ocr_configure_console: 'Configurar no console',

    // Painel de IA
    ai_title: 'Centro de IA/ML Alqvimia',
    ai_subtitle: 'Automação Inteligente Empresarial',
    ai_metrics: 'Métricas',
    ai_configuration: 'Configuração',
    ai_overview: 'Visão Geral',
    ai_process_mining: 'Process Mining',
    ai_task_mining: 'Task Mining',
    ai_doc_understanding: 'Document Understanding',
    ai_agentic: 'Agentic Automation',
    ai_comm_mining: 'Communications Mining',
    ai_test_suite: 'Test Suite',
    ai_documents_processed: 'Documentos Processados',
    ai_processes_discovered: 'Processos Descobertos',
    ai_tasks_automated: 'Tarefas Automatizadas',
    ai_time_saved: 'Tempo Economizado',
    ai_avg_accuracy: 'Precisão Média',
    ai_active_agents: 'Agentes Ativos',
    ai_modules: 'Módulos de IA/ML',
    ai_pm_desc: 'Descubra e analise processos de negócio',
    ai_tm_desc: 'Identifique tarefas automatizáveis',
    ai_du_desc: 'Extraia dados de documentos com IA',
    ai_aa_desc: 'Agentes autônomos inteligentes',
    ai_cm_desc: 'Analise e-mails, chats e chamadas',
    ai_ts_desc: 'Testes automatizados com IA',

    // Process Mining
    pm_title: 'Process Mining',
    pm_subtitle: 'Descubra, analise e otimize seus processos de negócio',
    pm_import_log: 'Importar Log',
    pm_new_analysis: 'Nova Análise',
    pm_variants: 'variantes',
    pm_cases_analyzed: 'Casos analisados',
    pm_avg_time: 'Tempo médio',
    pm_bottleneck: 'Gargalo',
    pm_view_map: 'Ver Mapa',
    pm_optimize: 'Otimizar',
    pm_visualization: 'Visualização de Processos',
    pm_select_process: 'Selecione um processo para ver seu mapa de fluxo interativo',

    // Task Mining
    tm_title: 'Task Mining',
    tm_subtitle: 'Descubra tarefas repetitivas candidatas para automação',
    tm_start_recording: 'Iniciar Gravação',
    tm_analyze_tasks: 'Analisar Tarefas',
    tm_detected_task: 'Tarefa Detectada',
    tm_frequency: 'Frequência/dia',
    tm_avg_time: 'Tempo Médio',
    tm_automatable: 'Automatizável',
    tm_priority: 'Prioridade',
    tm_action: 'Ação',
    tm_automate: 'Automatizar',
    tm_high: 'Alta',
    tm_medium: 'Média',
    tm_low: 'Baixa',
    tm_savings_potential: 'Potencial de Economia Estimado',
    tm_hours_month: 'Horas/mês economizáveis',
    tm_savings_month: 'Economia estimada/mês',
    tm_roi: 'ROI estimado',

    // Document Understanding
    du_title: 'Document Understanding (IDP)',
    du_subtitle: 'Processamento Inteligente de Documentos com Machine Learning',
    du_train_model: 'Treinar Modelo',
    du_process_docs: 'Processar Documentos',
    du_invoices: 'Faturas',
    du_contracts: 'Contratos',
    du_purchase_orders: 'Ordens de Compra',
    du_forms: 'Formulários',
    du_receipts: 'Recibos',
    du_id_documents: 'Documentos de ID',
    du_documents: 'documentos',
    du_accuracy: 'precisão',
    du_pipeline: 'Pipeline de Extração',
    du_digitization: 'Digitalização',
    du_digitization_desc: 'OCR e pré-processamento',
    du_classification: 'Classificação',
    du_classification_desc: 'ML classifica tipo de documento',
    du_extraction: 'Extração',
    du_extraction_desc: 'NER extrai campos-chave',
    du_validation: 'Validação',
    du_validation_desc: 'Regras de negócio e confiança',
    du_export: 'Exportação',
    du_export_desc: 'Integração com sistemas',
    du_extractable_fields: 'Campos Extraíveis (Exemplo: Fatura)',

    // Agentic Automation
    aa_title: 'Agentic Automation',
    aa_subtitle: 'Agentes autônomos inteligentes que trabalham por você',
    aa_create_agent: 'Criar Novo Agente',
    aa_tasks_executed: 'Tarefas executadas',
    aa_success_rate: 'Taxa de sucesso',
    aa_pause: 'Pausar',
    aa_start: 'Iniciar',
    aa_configure: 'Configurar',
    aa_capabilities: 'Capacidades dos Agentes',
    aa_decision_making: 'Tomada de decisão',
    aa_exception_handling: 'Tratamento de exceções',
    aa_continuous_learning: 'Aprendizado contínuo',
    aa_multi_agent: 'Colaboração multi-agente',
    aa_llm_integration: 'Integração com LLMs',
    aa_self_optimization: 'Auto-otimização',

    // Communications Mining
    cm_title: 'Communications Mining',
    cm_subtitle: 'Analise e-mails, chats e chamadas para descobrir insights',
    cm_connect_sources: 'Conectar Fontes',
    cm_emails: 'E-mails',
    cm_chats: 'Chats',
    cm_calls: 'Chamadas',
    cm_sentiment: 'Sentimento',
    cm_main_topics: 'Tópicos principais',
    cm_insights: 'Insights Descobertos',

    // Test Suite
    ts_title: 'Test Suite',
    ts_subtitle: 'Testes automatizados para seus workflows e robôs',
    ts_import_tests: 'Importar Testes',
    ts_run_suite: 'Executar Suite',
    ts_total_tests: 'Total de Testes',
    ts_passed: 'Aprovados',
    ts_failed: 'Reprovados',
    ts_skipped: 'Ignorados',
    ts_unit_tests: 'Testes Unitários',
    ts_unit_desc: 'Testes de ações individuais',
    ts_integration_tests: 'Testes de Integração',
    ts_integration_desc: 'Testes de fluxos completos',
    ts_e2e_tests: 'Testes E2E',
    ts_e2e_desc: 'Testes ponta a ponta',
    ts_success_rate: 'Taxa de sucesso',

    // Editor de Código
    ce_title: 'Editor de Código',
    ce_new_file: 'Novo arquivo',
    ce_save_file: 'Salvar',
    ce_run_code: 'Executar',
    ce_to_workflow: 'Para Workflow',
    ce_ai_commands: 'Comando IA',
    ce_voice: 'Voz',
    ce_stop: 'Parar',
    ce_console: 'Console',
    ce_clear_console: 'Limpar console',
    ce_ai_panel: 'Painel de IA',
    ce_explain: 'Explicar',
    ce_optimize: 'Otimizar',
    ce_refactor: 'Refatorar',
    ce_debug: 'Buscar Bugs',
    ce_document: 'Documentar',
    ce_test: 'Gerar Testes',
    ce_convert: 'Converter',
    ce_security: 'Segurança',
    ce_complete: 'Completar',
    ce_fix: 'Corrigir',
    ce_lines: 'linhas',
    ce_saved: 'Salvo',
    ce_unsaved: 'Não salvo',
    ce_listening: 'Ouvindo...',

    // Ajuda geral
    help_title: 'Como funciona?',
    help_close: 'Fechar ajuda',
    help_got_it: 'Entendi',
    help_learn_more: 'Saiba mais',
    help_tips: 'Dicas',
    help_shortcuts: 'Atalhos de teclado',

    // Ajuda Workflows
    help_wf_step1_title: 'Arraste ações',
    help_wf_step1_desc: 'Selecione ações do painel esquerdo e arraste-as para a área de trabalho.',
    help_wf_step2_title: 'Configure propriedades',
    help_wf_step2_desc: 'Clique em cada ação para configurar seus parâmetros no painel direito.',
    help_wf_step3_title: 'Conecte o fluxo',
    help_wf_step3_desc: 'As ações são executadas em ordem de cima para baixo.',
    help_wf_step4_title: 'Salve e execute',
    help_wf_step4_desc: 'Salve seu workflow e execute-o no Executor.',
    help_wf_tip_voice: 'Use comandos de voz para adicionar ações',
    help_wf_tip_debug: 'Use F9 para adicionar breakpoints',
    help_wf_tip_ai: 'Gere workflows com IA descrevendo o que você precisa',

    // Ajuda Editor de Código
    help_ce_step1_title: 'Escreva seu código',
    help_ce_step1_desc: 'Use o editor com destaque de sintaxe para escrever código.',
    help_ce_step2_title: 'Use comandos de IA',
    help_ce_step2_desc: 'Pressione Ctrl+I para invocar o assistente de IA.',
    help_ce_step3_title: 'Execute e teste',
    help_ce_step3_desc: 'Execute seu código e veja os resultados no console.',
    help_ce_step4_title: 'Exporte para Workflow',
    help_ce_step4_desc: 'Converta seu código em ações de workflow.',
    help_ce_tip_ai: 'A IA pode explicar, otimizar e refatorar código',
    help_ce_tip_voice: 'Dite código usando comandos de voz',

    // Ajuda AI Dashboard
    help_ai_step1_title: 'Explore os módulos',
    help_ai_step1_desc: 'Selecione entre Process Mining, Task Mining, IDP e mais.',
    help_ai_step2_title: 'Analise dados',
    help_ai_step2_desc: 'Importe logs e documentos para análise com IA.',
    help_ai_step3_title: 'Descubra insights',
    help_ai_step3_desc: 'A IA identifica padrões, gargalos e oportunidades.',
    help_ai_step4_title: 'Automatize',
    help_ai_step4_desc: 'Converta os insights em workflows automatizados.',
    help_ai_tip_pm: 'Process Mining descobre processos reais dos seus dados',
    help_ai_tip_idp: 'IDP extrai dados de faturas, contratos e mais',

    // Ajuda Gravador
    help_rec_step1_title: 'Inicie gravação',
    help_rec_step1_desc: 'Clique em Gravar para começar a capturar suas ações.',
    help_rec_step2_title: 'Realize as ações',
    help_rec_step2_desc: 'Navegue e execute as ações que deseja automatizar.',
    help_rec_step3_title: 'Pare e revise',
    help_rec_step3_desc: 'Pare a gravação e revise os passos capturados.',
    help_rec_step4_title: 'Gere workflow',
    help_rec_step4_desc: 'Converta a gravação em um workflow executável.',

    // Ajuda Configurações
    help_set_step1_title: 'Personalize sua experiência',
    help_set_step1_desc: 'Mude tema, idioma e preferências visuais.',
    help_set_step2_title: 'Configure integrações',
    help_set_step2_desc: 'Conecte com serviços externos como IA, OCR e mais.',
    help_set_step3_title: 'Gerencie credenciais',
    help_set_step3_desc: 'Armazene suas credenciais de forma segura.',

    // Mensagens
    msg_success: 'Sucesso',
    msg_error: 'Erro',
    msg_warning: 'Aviso',
    msg_info: 'Informação',
    msg_loading: 'Carregando...',
    msg_saving: 'Salvando...',
    msg_saved: 'Salvo com sucesso',
    msg_deleted: 'Excluído com sucesso',
    msg_copied: 'Copiado para a área de transferência',
    msg_no_data: 'Nenhum dado disponível',
    msg_confirm_delete: 'Tem certeza de que deseja excluir?',
    msg_unsaved_changes: 'Você tem alterações não salvas. Deseja continuar?',

    // Idiomas
    lang_spanish: 'Español',
    lang_english: 'English',
    lang_portuguese: 'Português',
    lang_select: 'Selecionar idioma',

    // Gravador
    rec_connect_first: 'Conecte-se ao servidor primeiro',
    rec_select_window: 'Por favor selecione uma janela para gravar',
    rec_target_window: 'Janela Alvo',
    rec_no_window: 'Nenhuma janela selecionada. Gravará em qualquer janela ativa.',
    rec_no_windows: 'Nenhuma janela aberta encontrada',
    rec_start_recording: 'Iniciar Gravação',
    rec_stop_recording: 'Parar',
    rec_pause: 'Pausar',
    rec_resume: 'Retomar',
    rec_capture_element: 'Capturar Elemento',
    rec_recorded_actions: 'Ações Gravadas',
    rec_no_actions: 'Nenhuma ação gravada',
    rec_save_workflow: 'Salvar como Workflow',
    rec_clear_recording: 'Limpar',
    rec_select_window_modal: 'Selecionar Janela para Gravar',
    rec_update_list: 'Atualizar Lista',
    rec_windows_found: 'janelas encontradas',
    rec_searching_windows: 'Buscando janelas abertas...',
    rec_no_windows_found: 'Nenhuma janela aberta encontrada',
    rec_open_app_refresh: 'Abra um aplicativo e atualize a lista',
    rec_configure_element: 'Configurar Elemento Capturado',
    rec_element_info: 'Informação do Elemento',
    rec_action_config: 'Configuração de Ação',
    rec_variable_name: 'Nome da Variável',
    rec_element_type: 'Tipo de Elemento',
    rec_action_type: 'Tipo de Ação',
    rec_wait_before: 'Espera antes (ms)',
    rec_wait_after: 'Espera depois (ms)',
    rec_capture_image: 'Capturar imagem do elemento',
    rec_description: 'Descrição (opcional)',
    rec_add_action: 'Adicionar Ação',
    rec_workflow_name: 'Nome do Workflow',
    rec_workflow_desc: 'Descrição',
    rec_summary: 'Resumo',
    rec_actions_count: 'ações'
  }
}

const LanguageContext = createContext()

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => {
    try {
      const saved = localStorage.getItem('alqvimia_language')
      console.log('[Language] Idioma cargado:', saved || 'es (default)')
      return saved || 'es'
    } catch (e) {
      console.warn('[Language] Error leyendo localStorage:', e)
      return 'es'
    }
  })

  // Guardar idioma cuando cambia
  useEffect(() => {
    try {
      localStorage.setItem('alqvimia_language', language)
      document.documentElement.lang = language
      console.log('[Language] Idioma guardado en localStorage:', language)
    } catch (e) {
      console.warn('[Language] Error guardando en localStorage:', e)
    }
  }, [language])

  const t = (key) => {
    return translations[language]?.[key] || translations.es[key] || key
  }

  const changeLanguage = (lang) => {
    if (translations[lang]) {
      console.log('[Language] Cambiando idioma de', language, 'a', lang)
      setLanguage(lang)
    }
  }

  const availableLanguages = [
    { code: 'es', name: 'Español', flag: '🇪🇸' },
    { code: 'en', name: 'English', flag: '🇺🇸' },
    { code: 'pt', name: 'Português', flag: '🇧🇷' }
  ]

  return (
    <LanguageContext.Provider value={{ language, t, changeLanguage, availableLanguages }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}

export default LanguageContext
